EXE=group_forage_dynprog.exe
CPP=group_forage_dynamic.cpp main.cpp
HPP=group_forage_dynamic.hpp parameters.hpp
CXX=g++
CXXFLAGS=-Wall -Wconversion -O3  -std=c++20

$(EXE) : $(CPP)
	$(CXX) $(CXXFLAGS) -o $(EXE) $(CPP)
